
[UpstreamProxy]
  Type = "none"

[Logging]
  Disable = false
  Level = "DEBUG"
  File = ""

[ClientLogging]
  Disable = false
  Level = "DEBUG"
  File = ""

[NonvotingAuthority]
  Address = "127.0.0.1:29483"
  IdentityPublicKeyPem = "auth1_id_pub_key.pem"
  LinkPublicKeyPem = "auth1_link_pub_key.pem"

[Debug]
  DisableDecoyTraffic = true
  CaseSensitiveUserIdentifiers = false
  PollingInterval = 50

[Panda]
  Receiver = "+panda"
  Provider = "provider1"
  BlobSize = 1000

[Reunion]
   Enable = false
