# Katzenpost server configuration file.

#
# The Server section contains mandatory information common to all nodes.
#

[Server]

  Identifier = "mix1"

  # Addresses are the IP address/port combinations that the server will bind
  # to for incoming connections.
  Addresses = [ "172.28.1.5:29485"]

  # DataDir is the absolute path to the server's state files.
  DataDir = "/conf/mix_data"

  IsProvider = false

#
# The PKI section contains the directory authority configuration.
#
#
# The PKI section contains the directory authority configuration.
#

[PKI]
  [PKI.Voting]
  [[PKI.Voting.Peers]]
    Addresses = ["172.28.1.10:21483"]
    IdentityPublicKeyPem = "auth1_id_pub_key.pem"
    LinkPublicKeyPem = "auth1_link_pub_key.pem"

  [[PKI.Voting.Peers]]
    Addresses = ["172.28.1.8:22483"]
    IdentityPublicKeyPem = "auth2_id_pub_key.pem"
    LinkPublicKeyPem = "auth2_link_pub_key.pem"

  [[PKI.Voting.Peers]]
    Addresses = ["172.28.1.9:23483"]
    IdentityPublicKeyPem = "auth3_id_pub_key.pem"
    LinkPublicKeyPem = "auth3_link_pub_key.pem"


#
# The Logging section controls the logging.
#

[Logging]

  # Disable disables logging entirely.
  Disable = false

  # File specifies the log file, if omitted stdout will be used.
  File = "/conf/mix_data/katzenpost.log"

  # Level specifies the log level out of `ERROR`, `WARNING`, `NOTICE`,
  # `INFO` and `DEBUG`.
  #
  # Warning: The `DEBUG` log level is unsafe for production use.
  Level = "DEBUG"