[UpstreamProxy]
   Type = "none"

#[UpstreamProxy]
#  Type = "socks5"
#  Network = "tcp"
#  Address = "127.0.0.1:9050"

[Logging]
  Disable = false
  Level = "NOTICE"
  File = ""

[Debug]
  PollingInterval = 1000
  DisableDecoyTraffic = false
  # PreferedTransports = ["onion"]

[VotingAuthority]
  [[VotingAuthority.Peers]]
# annares
Identifier = "annares"
Addresses = ["131.155.69.135:65534"]
IdentityPublicKey = """-----BEGIN ED25519 SPHINCS+ PUBLIC KEY-----
/fjoRTnyDITTtD1ialtNWSzfTp9Vd47kEUa7sc3LM2I+PRgv+JbeuaLpEbJLfAoR
K1Q/TqWuvrUThx2FvnRDMIQtUnlAUleZT/ScJJ2av9Qh0gx8v2yZG0TuqpCiJmY0
-----END ED25519 SPHINCS+ PUBLIC KEY-----
"""
      LinkPublicKey = """-----BEGIN KYBER768-X25519 PUBLIC KEY-----
7NNX023odnDnPM5oB9jR+A6onG4Af3hfU+pjtu2j3Sm8jCR3R5ct9JYSw2H8VcLB
lj+k9Jb+I2MmhzT0gCK/yYbWC1R7UjZqlKJLtXZFjA3TuIX4wHfXUpn9+HUSA4hz
Bn1v8RALFg5kJrmxSK/5BJQIoSoDUCVdoF4Rp5dhEFpXolqscI2T1lY9Kp+jgSZ2
uKiTFUrvZHuvYx4NnFheFW7/lwiFJUi9ZZeX4YHdBB1MTEIcQFHdjH8JPJWGvHht
zCg8JjNTO79j5b47YJb+GFbiQW/E2Jo5py/4KXNAJHT19Kl8WM6zNRAfxaHpFcJH
axwzWbTlhc1E7JeIqci98paZsn7o8w3yVpS8sBH9DMPE2TgweqchZMx6VT01oy7R
5jlysJkA6k+IBDcC3CY/iFIPhsw+2Fy4FxVgoLx30VQ2qC2pqEBKqltZJDYdBJaP
hoISrFm9anr5JTRJE5vj6VM3BbiHNncP+0g9SJOHAJcORR2tXEL4oItKo1w9ZiKF
21uCcQx2Kpf72ppwpAmq+1959a9Q/Ap/ZALRDC3G1lzNd2O6830dZ49UOVJaSRHU
AzTFwEN6R4iy0UjZGGx+gDMQbFhB5aJasYwMiFj2QQZahheRo4TLyVBHKUv8lAGr
u3cQNy9A4x4ZaSATSxlMUy2kbDVGEwhStM3jcojZysUI6cBAMsmJvMlcmVfO8gyF
diFw2Du4vE5F08wXi7URKS412192mZKNGXSXVoz0KXaxE5j5B3gvEM2MmpR7m7UL
DFQmjD3zpb11ma1lpHiiqTVl8FuPcE19FSRflw+k6p4TR7N6U1dEaor3mMGIyw+C
Urq1OgiREhJn2ZGiBQkLy4q0WWPxEZsD0JrNIT899mulZmxe8UhNBmSfR54/lr8y
0Qlp8Huu3CpgU8vT5sOxCxeQlm3kqCkMlyepVwPAdygU6Dv2wDQTu8GqURyiCqxC
zKCABjskqicEx8tjcSY0kRFtxG7Uch1+u01KWq1UbBlilby4+8n+mbwC1xFhCE6L
dWwM9bJTx75nYHkTlIbr1hYwobHxp4AgBGg7+7WLiFV06UuWiaYjIEZnZLyNsaGC
qYX1koH0xzdjYQxy+4HMuiBBFoB96J7TVhTH9CnbgUtQLKHearqzS49AVIiC3A7U
Wmn9KcIve5xTt69qYFew+G39imdo8aCHiFEGupoXAnhG65XnTLFbqm+SA0PSAKCw
63gklJlvRBjQChZNOz50gDwNTDiKiHTpwYLURybYuGfsRVuSt6M/eKn8JTU22R2H
DMGeZUgXISuHAhNtS6M5SoKiGSQN6FgXhzIAzF+NdVyWuRjOy5Tv+W0p2VYVmssw
o8Z5RWUatkOwODVsMmIdNkGHR3ZWmDBng3lK2wGyIma84241Bmg3jJoZ4HzayY7p
RYNM+Uwp2blw9379G4xUSyD/BYHrIJe3Mwyqdc8sl2xTd1FoQhDGwz/PIoT/KE9m
hm8ySnLAh52a0CsVDKFgYWY6MGJRupt0aiQXIzCZQUdgWsE6AnxHzBgHsAhemrhG
9Z8G8zErRaYUnEd2CFeMIMg/qX0dYAH8ubMR4I2oh0vPYrxFZE8uBOeQ/x2Yln22
/xjAgyrIczt5s4YYPzd2yg==
-----END KYBER768-X25519 PUBLIC KEY-----
"""


  [[VotingAuthority.Peers]]
# beeblebrox
Identifier = "beeblebrox"
Addresses = ["37.218.247.39:3333"]
IdentityPublicKey = """-----BEGIN ED25519 SPHINCS+ PUBLIC KEY-----
sffL6SrX94zltrKWiCc1bxvgqPaKuCpUsErChV3bUEop4+YrTXDMgH3JzKemFBf8
nmKjcV8le0fvASF0COhBdCoSse7YWSuR0zCiB1YiZk4nkfyhClxcTmXMV4hY7pvp
-----END ED25519 SPHINCS+ PUBLIC KEY-----
"""
      LinkPublicKey = """-----BEGIN KYBER768-X25519 PUBLIC KEY-----
4X5ezeYQSDsLZ9RBpIYGw3RUnj/trGRjwzD0ToFixV64VT9REsQMynI7BXtDtSLw
yld5CR3ld2EPmUryF2gnODOTl5rzVWuXpALXyspscm3IZr1fayIphjqkpmy4cmjo
RoViwVxQRspZcBjjUaGtc4KyAYs+A56tYGA7dRBGoWmg2wbqYlhy4LRuk4sAQsjg
o6nuRzPcFQCk4SZnuwTN9YpiIkS0krbK9bIMc6/tywRblpnXaYFl7LASyKmwoacK
BwSoBZBdu17PhR9YtI0gRSe2DHco07lVIXiQsEPduF49I7c2HJP5hyY0ggeoRW32
C1C0kRXoJlyhJ2RmfHqDBEGvx2Djsm4i+sxLK3kJOEy3zHpKRlF2lEM8+lftoqiO
RAeIql6/IJeWMTq9FcIJ1MOrExJQRjK2WScZ2ZBxOglX48ATNz0pW4bkVxK4cmd2
p8K4qkuqaRZUYCvuUmTuRp/vCIKTN0x6uBkXmp/PGsQ/c4NzkW3lK7veAB5JdZFZ
jHWOMDYoFmLV+K06ZiN61HsPMXWW9VnJsFm/UnVKJrGQc4Vqe0bHdoyoQ2XAqsa6
c31ARi3RmbSN9ydgqFs54Lx6hYxG6RlcAm16kSr1dXhj/IUHbGztqWZCq1kXmKZM
kx3yV64ReUu06WQ/+qylLAULIBNdmWLA+XJo6JrZxsCr1jRA1nfEjLomaceIc65s
AyFOmUITLBf29GBeVEnJyYNodKRL2crAOEmZFSu5ErXEyBBn44t8vLyKeb4WU2RM
cp00NLrHZ122ZV/9UWGXkGNXMhTFkcNOMJ4oZwy1OI4KmYki2RfztlR+e61B5Wcx
FCT0p73DkYOCGKz+6WAouqjSmrTixmcisDiyMV9ntDIdF8HXCbN82WUVUUPaaYZN
hW3AZoV0G6tU12sXt5x5o5h61hn5pUGgOLKulHxylMCyCWMUIAddKmowRLOkIIx9
ID1FQT6j0pFixAwKiyquQYgaCWgNEClM9ZD30miXNJXKI1yKQTTGW2JOd5qvpX7q
0ytfYaS3BXaOiU/DzEDoYpbrRTi80BSDh4e8YjtOdVKyJh5DWRpL0ivYLAXeR84s
yjG2IyZ1OJaY1quj2Yk5ySLcApFAKcQI+HS6B89lOEJM1iknAjeNZz20Bbq1xlUM
pjmiMVTE1gDWuh3552mmOLoPk7fIWX/gEoxtOAPxmoOTc4bTWTLn2ZuETGPkuHRu
0wrJG0B7BEbk47N3eYPR4Z2haJIKM6GhQ4//0aRFsSqHO6vocYE5w0oLlGZMXLeZ
yV47NgURW75vYQPeqnzNYVYpubNQcAJmfE0smqpCtb+MCViz4ivjc02Y0sQ71M1p
069mBh0R1CkcsBEBMaHpOQllORn5zMVgwheSZnhxNW4JYxXxIiId9XhzdA2zNltp
SKI8BiOoRR3C422Ql1SwNhke9TMPGKVT6Bt+pT5/OKkWsSgR5EQBNk9UGCett2JO
G7Cvt4gHu3MgMcoigQqx8lxGC779gGl88g9GQ6phtEQz4cxh/DhiFKeicp7c8Ysp
ECnmeSgruGKGJKiIoavE5HcDt3RB/LThxYzpw0UtQi6HAlnm81rXOMNcj0PYaGSY
VSZNStzaExhQ9wxg7HeRaQ==
-----END KYBER768-X25519 PUBLIC KEY-----
"""

  [[VotingAuthority.Peers]]
# gnunet
Identifier = "gnunet"
Addresses = [ "131.159.74.69:65534", "[2001:4ca0:2001:42:225:90ff:fe6b:d60]:65534" ]
IdentityPublicKey = """-----BEGIN ED25519 SPHINCS+ PUBLIC KEY-----
jclECUIi0bp4f627W/T3q/bVZTV/zBYiT4Ry/9RlTpEr7ul+qPLGaHNbtPwH1kxD
86iP48/CFAz8W0RVnwtGm14wruOrE1d02917Qn7StkVVDxRMyf8yyGY7pis1wgBL
-----END ED25519 SPHINCS+ PUBLIC KEY-----
"""
      # from gnunet_auth_id_link_key.pem
      LinkPublicKey = """-----BEGIN KYBER768-X25519 PUBLIC KEY-----
X+8liX6+O1jT7IAub2R/cC3d92V+JLl0xN7GjYWHr1TipqTHJBsj+4HRKMHNYGzG
/Aq3YsU+uiW1Spfn6BZOCbST5ggDNgzepYcVZ6TYwXhsgIk651PrIVtyMQ2MRTHw
CBDAG7DBuC+f04XWlbib/JXzUE+4pjziAqX8kTdNAUrgVwcOMjrD5U46yWD+86EX
IDcOYl/r9R2ca8RR+TNjtHFvFAPx1AQ6kUftgbUiFnGzZ4q1c7xdpCCMeCPdas8m
ycW52yKBOHgX6cp6Gp7eBH47y7TDx51VAJSz4IZTQ220hpX4KXl/e815eRC0CwGj
JzFXSH52wZDf1UTXca5iYcF1kMnYRRQ/CTWw+5b+Y6jhAp1P+0flEVqG0zyql2v/
I80usqTuoh07BYFyXJIJ1MAYM0e2tb9BGElXwRJKyl8xKF5r4AOVBnaZBclZhKM5
+W57ByWMSS13w0K5ccXyLLfxOI6lIKgZparhBgz81BFld7/xyGEkjKaK65PVyI/5
wE18SRB4NnTmNYrNFgDytFIKaZr2ilPUiodsBLKCQYc7VaJLAcbBomCAQDCThnM8
IlR1RhW5cKIP8s+YsbZyyiCZTFoPDDOK1y5FG4x5WXUZ2WCQMUGamHW6QjHOIIBg
kKusYERXl4VzgJ7uAA4dFwKT1RUrKVaFShw86qBDmjwMx4OX8lJDAz7HkhCDagV+
dwfIop6bAC+VllpYUSE6KYbNY6p1hHU0C10wq7+a7LubQ5n49CncEWalQSktJ1mZ
KEzh8VpSCT+4gCN0q8Qwm03uZUFo4ENwiwqG0ieHyz+KKW220JhT1rPXugjhxAKx
u0uHa1yToxHR4E3/TE9Hw39rmVTAsiE1Y1mPVsR9kafco1aap4BVAT7gG0dqlZS6
l7GN+ogpIqAMsI+PhFXoChynw2TEAgVKuwkrJRYoaAusuh++Ch2Z6hPdJ1B1Glrc
GwYITGzmWR/tdTBV4IiTmX0Z+J7Vuyzxd2MGJa5ukJO/RBCt9GK8QA5BkAhkJYmR
U8gm1lrXmEkjdTvrSpUB0HEKsGYgwF2O9J5S+LxZEAEj+VvIcsf8tCi+5iUBqTDp
JxScmqRB0H7sIWIg8jyl4VEIIDCm+SORtKo8HDOzoMVcqk5WeTNtgcFa15ZAhIpM
+VHGJI+O9TQEGVxq7HTC3Cl1wZr52iivG6QFuyc5xYHi6kwle2J7OUPNiss14bPz
KwEzubCMp36LtkT32LTbPBHUpIjo6zoCC3XbIUVX2IoBihu24FejanawQjonnGxQ
LEL2fFofNse78YcdHCni4URBbCUe8wmtBRn7FC+RYC7DGTHkK7Yjyh8hpaMtmj4I
u1GZ8ln10DGhQkPGm1T6KRLPRUSV1lIiBqssSxV0kJofJCy9ZWSiYwfCNFCiaBd+
Zk+YfEmaCiXEqktLgIupR2AtZBlz/LT+Ixx1WM1ys8MFVE+Rh0M2AL/wE4elmc6S
pn+9aoQZMkB4wmlTulvrzHiLJ5o6c22magdGuzFRCoDQpKbYGsDrsgkkURAbzJjO
scRn1VnYgQ/tJ5aeBcqyhhhVJjxP54WjPBtLMbTXqS8wCPB3ghstPVJ7W7+fam4r
feOstL0pARWr1YI6PonRbQ==
-----END KYBER768-X25519 PUBLIC KEY-----
"""

  [[VotingAuthority.Peers]]
# marighella
Identifier = "marighella"
Addresses = [ "191.101.71.152:40000", "[2a02:4780:14:af58::1]:40000" ]
IdentityPublicKey = """-----BEGIN ED25519 SPHINCS+ PUBLIC KEY-----
cEAu8JISHrc9n45xz6vUkJfvPnf3LlzowA0pyc443q+TAWiB5+NaRgK42Y01hDiK
m0bmjPCQnMjcLEPTRVjdHirHTZXQLJq+w2i0ubNhI/nFn1Xka08WHpvLYC+XqgM5
-----END ED25519 SPHINCS+ PUBLIC KEY-----
"""
      LinkPublicKey = """-----BEGIN KYBER768-X25519 PUBLIC KEY-----
5Mr5o0xywq18GdC8l7JGcLNhzRTNqpPIvSA6q4XTIyeo4m0p9pORJ3gwmndUGHZE
0r+nu1o5crS46VGC4Xa6+mHdrDgVpr3SEI1FaIZ6Na4/JVWkkspUCSWQ0G1ESjY3
ZYORWR8rbEI24h2YCYKz9n0wNKr2R4kD3AFpyipsqAYJx71Ikmvd8lLIAI9twT6n
OhU6+4THGC07FWxBpIm1CaXSRB/q/C2/AzsBHEY6pxmQKDwteqLzazWN21bw8pwj
q659ka1deEbJ4BcyEb+jJmDqOos3cg85Bz73tw9LHAL3VgZwk2THJEJz1BUIWkeo
cs3Hwp5Ty3Wkd4wddjrPtwLBNZlqIWC8VEm7tKvcRQ6po13IkTRqyQYfkMVuxEMd
8nT+prsVJofnQjTkR1NTAGwDQxVv6jqUCkXluJ352BK6FrTo8326GnCiJhx4tRNc
tYt9cKjMW3lfbHFsii5ThS2NQY+WYQ0Qiab3o6t+8D4LFUBvNjhtiLhLlRuQ27gT
QTt+1keEhEKHN7CJhyfcfAcDwbz3RkkOqcLy46CXVowWaZlLNLQ/ej8Rd32fw7Nf
QU0Qy3iw6qFNHArSQEyJzEVYsgVR87nc+SArdo98dj/le5WbhSnmcAFbAlvmYSy/
k2mNgqtRhky8im9eYF7zkhuT6jUbmxDS58r1C2QOm349cRqv55b9rIj0oDchETUC
i06EKEIXErho5JOydI3Y57Au5SrKRU1BuUAk7IkZ1yY6I2cxyXIAEmWvC0pyN1Co
58HMO6LXwCmzyLNrZ6Rc7LJ4p5MKGzY98EXZ1w895GitACcu5gtzhlTkBT2SlzS0
bJ+7kR0yJHjr8A1jukIASZ4IZVz/Ujz18oCn13rwdqP00ytBManzEpArYnjR6FEO
pKzciEI7dDOKcDNsXCdItnXwsZWVsJmUEF+z54D0pItNQivbFRXPkYApEXEXaZLi
5kAmh287MEGuQqzup0SLIlmrnITaNoMhi2P6R1wqe6AAiZDSIiAcY7E06xoqo8D5
uGtxx52zkUFZLH/gGE/DAsvHNl2ltC/oezFKfHQ/aSNJzGbx63sdKZlf08l/wUSN
CwaIABgIQ3WnqkXnxXjFpCqTJSbzNBnZ1RwClwmHQxdn1rPJtTzzsWUexkOdJmmp
5cBAHB0fULJ35woIeT6ZpXcl0rsDa6klm1nepzYpo18qKgcDKLzpFScIhIA98o9h
+Ed1Z6/pJqWfhqvey1gt+EQ6ZWUS+HuS6p0kchS4Rro32VZ8Q0uC0VA2t5RIsETg
EW70s4TuQCWwNjtHJBsBpSAPFqIy6GAetxzRoM1GJ7bGklUqtrCo1zlJY55tZh7d
tDVBVk5EcnJL4ir2BSZM51U2lJwIEZPclyO6Oo9lBxNIqyqbeXAymkV8iWqe/BWv
Qgzlgj89Z58vkDIFcUL6asjqhhqqzCro2lSFKSqtbD/WU8Nw0mxaAEBlGoyR6i8X
05hQG7Gqh805tJj/InNi54+TNICZe5wzVoLW6GiWMV8iJMg1uhSTN1gk+yKG/Gl0
d7pNKav+/Mrl4pfWQT5/kSMNHI+m61VemmQ3HJ5HoSbROjoS4ndumaOAOnFFVUAl
1+F2LV8O/F13m4S4g1tj8g==
-----END KYBER768-X25519 PUBLIC KEY-----
"""

  [[VotingAuthority.Peers]]
# nutria
Identifier = "nutria"
Addresses = ["65.108.220.173:40000", "[2a01:4f9:c011:4e7b::1]:40000"]
IdentityPublicKey = """-----BEGIN ED25519 SPHINCS+ PUBLIC KEY-----
TUchIOZ98fc7UABosstqDlRN7aRQtKk/NTeVkhoNdSI62g883BupqMBY2RafKJfS
l2WZdf75HCsxMigPJwQhB64HD8i+cg2VgLF0ndZh703HnNjiv1EH+2Z2uYH3El6Z
-----END ED25519 SPHINCS+ PUBLIC KEY-----
"""
      LinkPublicKey = """-----BEGIN KYBER768-X25519 PUBLIC KEY-----
eoRieDZr+HV4lqUcEtLRUzJKQ0anel3dEsm737d0TwW3l6zwsMDm8kaW7BuwRT4d
53Bs98rpgGxrvMWFagQdHE9jnITJ02m3I4GJwJJQgj2pZ4py0ckBK3/cdKXK6FVU
KZtuywueUKCLci2RGD6/GRYDdJV5yplQs58kBDAgSaUFY2d6VCnaSrdP1UnVmiWB
lJitY76X6yjqN6LeApTdGR0CTLGdZa9tBh466bWXtXcnap1GCTCR4YR2GQzo2Wdp
GkmLcydO+Q+cEJXYd3Mg5mA7ZbCFpBF8kUfiSlxySaVppMtmc7qozElDI2lMCFcf
YTtXtYqB4lh/gSK5EU/p4rzJc04MKG4Wk0gfo7ofOlbdsZc8eT+SUxcr0JA35iy+
mTCiS4Il8BxgRKxGFa0dOEGaqrbVZRZJ2IsdBqwAiZa5m51v6iieCS7jlFcIFkaJ
I8O+a0mZZ5p2V2NeEbRht4RUcbOajDm4dySwaQEa5jTS9HLPQc6l1z5RtzuZvE1u
E1YjdwGDi5sfc3ZhFqUNDDgLOHPmBptLyV8lSGk3u2LUMgudBkP/DKx+kUHhFjUs
ljjVCiRiRn3RSmwZ0jjTwrnCkRfpKKn3Sro/MlWkkqK+9kn4YR2397gqkpqOczJa
SoHhND6BELcJGBRlSl8iOD8i7J5beaoyNKgWbElzE4xfrGUNRoLFCjdXBZkeWDhL
HJYgoVPHGwOoPC6mtWGjFRGoeqJth4SvdBKiECwol0+6QJGHtIx8DIabA2m7nDoI
gEgOU8XL12pIKzIMbLik4SEBnLg3uH9D5mm/oyBTmUSud7+rRLekcK4bqGuH427K
EJ50Nsy71DVju4dWpsS9MshU160xoGwfFAUb8LfCmsgQiZQjGJ0DqcFeOqC/GpUM
uMoEQyQlkrLuMp5y66+xQai567CoksxdxnngjBFOipkToS0eIBVnk8DmSs4qg2pS
Rb2gmUusTGUsN2iAWMFVdAOCxWDbUJ8thLhEaRVyJj4cqTcyoX7v0Q5AWEY9CplN
GDZSmrU2liIGNj+kyUGeAgKWFKi69YNMqH8Ax6TmuaGe40fZ7IoVCxk+WUZnJTof
AHZjk0vzOQ5QMr81ODV0smlJJbJg2HGoBamIbDdLFldgU8HsgG066IJK4Z1+ZxYc
xJ0+CDrayFENQIc32VABibnxsgU/FokhIHcIfG2UtjO0lhaQelTOkj9BTMPjpJ+s
IGjM0II9SYBtqGH5lxikfKlmohgIWc/EVqIHSLCZg7mnFjdUY0BTeyAJGiX5ZCSp
KsgdAIp8ML9J+mySyM+DPLgheBClRApT2xZ+bAzcYosShiFuqnmu+2mFSLGr9lkv
5SboAL8/ZIXQ11zMJ34uqieq0W2UpYkf+m6+e5j8swAdyhKlFR0jmRNfhpKc+cvB
qmE71M5dRKqpyZZBVULpMnSBwVtvyrfJQDABO7TreVMmcjF6hQjiSj4I6F/44AjX
J5+teBYtVEqWuIq6FkbZAXKd8nv1psIJ9Y3DqDTT3LMztlrF8X/GclTeMXn32A3U
Zr/rFB4vmUBVk6N9dA8cBhyGIW8tQ8O17LyE4hXtWjvmEbFffh8Si1kegPKObPTS
xKymaSdIB5pbFkGCV1C0ew==
-----END KYBER768-X25519 PUBLIC KEY-----
"""

  [[VotingAuthority.Peers]]
# windfall
Identifier = "windfall"
Addresses = ["74.50.67.182:40002"]
IdentityPublicKey = """-----BEGIN ED25519 SPHINCS+ PUBLIC KEY-----
+oxlrZurSc3JD/eJsRmSabtFVsbFB/N1fSZSHTEajndgX/rGGZTCiBqMDqXC/qTS
dfvVb+yOmo+pnbnEeWuCecXFplODH92p83pp+nzmMadGUprzadL9smufJlb7+GkD
-----END ED25519 SPHINCS+ PUBLIC KEY-----
"""
      LinkPublicKey = """-----BEGIN KYBER768-X25519 PUBLIC KEY-----
MaoZ3OQXJXvoWu9v9Yq5aq+adWwzfAm8FYYXM0olCCXxTKnR/FPRoJKEGTtOU7VA
VqgtGcFyFoxctB82pAapdjcn1FHxXMjUyMWUh4810MRiAVgU9F3/BKuv/HVholmX
KLlRegvlhcf+VQlsAVDbXA3d87nHbG7gRqEARkRniTh4FlAok0eecZPmFkbt5EgT
mcziKq75+HeF1hgvB7pd1jy+tBLlhTE6FoMcBZSWyEFO1jQLxsQVVmtJa6+G6WwM
CJz0t1EVSlY9kC2Ze2y1FpS4ZlVFQC2gkxvu6q3/67T4ykzxc1pNuHSX+ClfJ2wu
8TJnEJqL9D/xsIORS5/l7DmoMRwd1cl24cpN0lQ464Heur0Bg6nr5LwlcbM+eKFx
Uik94wnW6JqI4r8eOTF/Qz6kuKUCqU3Yq3YKdqfwKo0apiogd4d1aIaTGBhxwbsn
XAOs3LfohlpXnEMQGw5r9ExKZnFDWpXZAsXE4roKJ1/foVRfgMjPqnQ3S0LMOsMs
44G83Hd+anUQ5lKXNB89NFIVZ479FoGApGgAtn7nAcPQAAbv83ElGQ7gpQjzkCOJ
6sfyFzSNSSdzK4YXdbHwnIplMCBZuylm8QsYsa2IuhR811XJ5EiGQkmIpjsnwiNe
tJBYhSczB5WiIVTkHJJPoKeAI6xEWDke+kxUR8EsdhVPZDBXEU6le2Ttiju0/J2v
+WLM81fV2h/+SxMOt0uhXJDWBX34IzU1loGZQlhEmBh04lCMhTXXmlzlpjBRF1+A
YsHnAgYs5bjCRhZCYI5KSwrf5TZ/NTKzqK64eJlGjF8/1WSMJneXyE0QJmz2YQqm
gFSvgFLyNXLecFxJiq0ml095cz5sopzBFg8D07mtgpWaGkWgbDY1F2YCc2kygwfu
8bXIN7yX5llDPF5RAcDOekVvAln826/EuzDbpA9ek1a3DC4oaqvqKMos+cFlSaCF
YExGaSpUhZVMMcHDQav7u0bhV5R4x55dJkzFciEpUwEb/Eb1I3qEAbb4CD5YQJGw
uzgQ6hX7AwGSJKcnsbcMExs56LkoFZ9FYDaRLFwDh83qUJGBqi+BLF6ryU7/5zYo
WH+Nt3dd4lryasggsYQkMym714XK95uF9Zv9esUUQhPK1ZdxCUI0U80zV1YFPIsf
1l9D5K+zgGGpK6YZZwS8tsppFyvqRKA7sGBwopYCNcFANsiFNAIkRxAFgSVWWbVE
RL3Zt6comB4PNszXHLbKVwjbs4NUxyrZ+pD2oALIBqGYC2aMTDk80CgdzF/Awg2J
4XATEHmOJ5fwV7GepRy7XDxvFb9UAhD4o5oNB7za0FfahySEvLVeKYOl4WsTUIEJ
TDIetFrfpJ2FeDAK+EaAOBGKaMvv9XSVSIPZxinC2yNYi3TQ53M3W33nemGtVcXQ
yrq1kMVuC4EozLxgycOWpkr9XAdtyIzTB7uJhby7Fqem0L5BhBnhcqH9kF1rB1M7
onmS01k6RBL2tB38AkcFpykFeVoQ1FT8tW22pTQFo88RIowRcT4YQmq2LKThpRHx
EQQMNqHcB8Z61ya7aG6K9wHLlnNpF0ZPV8n4k0Sp1QmJGJYt7/HMTAIK/ZHtHoQf
vkdQm1uuoKMh1qC6oRRsgQ==
-----END KYBER768-X25519 PUBLIC KEY-----
"""
